spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookingMedicalSystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Chuỗi bí mật JWT
app.jwt.secret=ChonMotChuoiKyTuSieuDaiVaBaoMatTren32KyTuKhongTheBiBeKhoa1234567890

# Thời gian hết hạn Access Token
app.jwt.access-token-expiration=900000

# Thời gian hết hạn Refresh Token
app.jwt.refresh-token-expiration=604800000